# Generated by Django 4.2.5 on 2023-10-25 15:42

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=members.models.upload_to_img_directory)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
