# Generated by Django 4.2.5 on 2023-12-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
            ],
        ),
    ]
